// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ShortenURLGenerator is an autogenerated mock type for the ShortenURLGenerator type
type ShortenURLGenerator struct {
	mock.Mock
}

// GenerateShortenURL provides a mock function with given fields: url
func (_m *ShortenURLGenerator) GenerateShortenURL(url string) string {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for GenerateShortenURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewShortenURLGenerator creates a new instance of ShortenURLGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenURLGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenURLGenerator {
	mock := &ShortenURLGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
