// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/christapa/tinyurl/internal/tinyurl/domain"
	mock "github.com/stretchr/testify/mock"
)

// UrlRepository is an autogenerated mock type for the UrlRepository type
type UrlRepository struct {
	mock.Mock
}

// DeleteUrl provides a mock function with given fields: ctx, shortUrl
func (_m *UrlRepository) DeleteUrl(ctx context.Context, shortUrl string) error {
	ret := _m.Called(ctx, shortUrl)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUrl")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, shortUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUrl provides a mock function with given fields: ctx, shortUrl
func (_m *UrlRepository) GetUrl(ctx context.Context, shortUrl string) (domain.Url, error) {
	ret := _m.Called(ctx, shortUrl)

	if len(ret) == 0 {
		panic("no return value specified for GetUrl")
	}

	var r0 domain.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Url, error)); ok {
		return rf(ctx, shortUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Url); ok {
		r0 = rf(ctx, shortUrl)
	} else {
		r0 = ret.Get(0).(domain.Url)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementCounter provides a mock function with given fields: ctx, shortUrl
func (_m *UrlRepository) IncrementCounter(ctx context.Context, shortUrl string) error {
	ret := _m.Called(ctx, shortUrl)

	if len(ret) == 0 {
		panic("no return value specified for IncrementCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, shortUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreUrl provides a mock function with given fields: ctx, url
func (_m *UrlRepository) StoreUrl(ctx context.Context, url domain.Url) (domain.Url, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for StoreUrl")
	}

	var r0 domain.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Url) (domain.Url, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Url) domain.Url); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(domain.Url)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Url) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUrlRepository creates a new instance of UrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlRepository {
	mock := &UrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
