// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package http

// URL defines model for URL.
type URL struct {
	// ExpirationDate Unix timestamp in seconds for the expiration date of the shortened URL.
	ExpirationDate *int `json:"expirationDate,omitempty"`

	// OriginalUrl The original URL
	OriginalUrl string `json:"originalUrl"`

	// ShortenedUrl The shortened URL
	ShortenedUrl string `json:"shortenedUrl"`
}

// PostCreateJSONBody defines parameters for PostCreate.
type PostCreateJSONBody struct {
	// ExpirationDate Unix timestamp in seconds for the expiration date of the shortened URL.
	ExpirationDate *int `json:"expirationDate,omitempty"`

	// OriginalUrl The original URL to be shortened
	OriginalUrl string `json:"originalUrl"`
}

// PostCreateJSONRequestBody defines body for PostCreate for application/json ContentType.
type PostCreateJSONRequestBody PostCreateJSONBody
